# .goreleaser.yaml
builds:
  - binary: twitch-exporter
    env:
      - CGO_ENABLED=0
    ldflags:
    - -X github.com/coolapso/go-live-server/cmd.Version={{.Version}}

    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

announce:
  discord:
    enabled: true
