name: Docker
on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [published, released, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-tags: true
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set tag
        run: echo "DOCKER_TAG=$(git describe --tags --abbrev=0 | sed -E 's/^v//g')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: coolapso/youtube-exporter:latest,coolapso/youtube-exporter:${{ env.DOCKER_TAG }}

