name: Release
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  tests:
    uses: coolapso/prometheus-youtube-exporter/.github/workflows/test.yaml@main

  release:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semrel.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          custom-arguments: '--commit-analyzer-opt patch_release_rules=fix,ref,build'
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: coolapso/youtube-exporter
    
  docker:
    needs: release
    uses: coolapso/prometheus-youtube-exporter/.github/workflows/docker.yaml@main
    if: ${{ needs.release.outputs.version != '' }}
    secrets: inherit
    with:
      release_tag: ${{ needs.release.outputs.version }}

